/**
 * Opportunity Lifecycle — lifecycle states for builder opportunity recommendations.
 *
 * P0-6 from BRANDOPS_NEXT_CAPABILITIES.md.
 *
 * Existing: CRM Opportunity has lifecycle (prospect → won/lost), builder OpportunityRecommendation
 * is transient with no lifecycle.
 * Missing: lifecycle states for recommendations, dismissal tracking, rediscovery prevention.
 */

import type { OpportunityRecommendation, OpportunityCategory } from '../../types/builder';

// ---------------------------------------------------------------------------
// Lifecycle Types
// ---------------------------------------------------------------------------

/** Lifecycle states for builder opportunity signals. */
export type OpportunityLifecycleState =
  | 'DETECTED'           // Newly generated by the radar
  | 'QUALIFIED'          // Passed initial relevance check
  | 'SAVED'              // User saved it (will act later)
  | 'DISMISSED'          // User dismissed it (should not be rediscovered)
  | 'PLANNED'            // Converted into a Plan
  | 'ACTED'             // Plan was executed
  | 'OUTCOME_OBSERVED'  // Outcome was observed/verified
  | 'LEARNED'            // Lessons were extracted; signal is fully processed

/** Human-readable label for each state. */
export function lifecycleStateLabel(state: OpportunityLifecycleState): string {
  switch (state) {
    case 'DETECTED': return 'Detected';
    case 'QUALIFIED': return 'Qualified';
    case 'SAVED': return 'Saved';
    case 'DISMISSED': return 'Dismissed';
    case 'PLANNED': return 'Planned';
    case 'ACTED': return 'Acted';
    case 'OUTCOME_OBSERVED': return 'Outcome Observed';
    case 'LEARNED': return 'Learned';
  }
}

/** Transition timestamps for a signal's lifecycle. */
export interface LifecycleTransitions {
  /** When the signal entered each state (ISO timestamp). */
  DETECTED?: string;
  QUALIFIED?: string;
  SAVED?: string;
  DISMISSED?: string;
  PLANNED?: string;
  ACTED?: string;
  OUTCOME_OBSERVED?: string;
  LEARNED?: string;
}

/** A builder opportunity signal with full lifecycle tracking. */
export interface OpportunitySignal {
  /** Stable id. */
  id: string;
  /** Workspace id. */
  workspaceId: string;
  /** Category. */
  category: OpportunityCategory;
  /** Title. */
  title: string;
  /** Description. */
  description: string;
  /** Reason this signal was generated. */
  reason: string;
  /** Evidence references. */
  evidence: Array<{
    ref: string;
    kind: string;
    label: string;
  }>;
  /** Confidence (0-1). */
  confidence: number;
  /** Expected value (0-1). */
  expectedValue: number;
  /** Effort level. */
  effort: 'low' | 'medium' | 'high';
  /** Goal alignment tags. */
  goalAlignment: string[];
  /** Primary action. */
  primaryAction: string;
  /** Available actions. */
  actions: Array<{
    type: string;
    label: string;
    targetId?: string;
  }>;
  /** Current lifecycle state. */
  lifecycleState: OpportunityLifecycleState;
  /** Transition timestamps. */
  transitions: LifecycleTransitions;
  /** When created. */
  createdAt: string;
  /** When last updated. */
  updatedAt: string;
  /** Dismissal reason (if dismissed). */
  dismissedReason?: string;
  /** Saved plan id (if saved/converted). */
  savedPlanId?: string;
  /** Execution id (if acted upon). */
  actedExecutionId?: string;
  /** Outcome observation (if observed). */
  outcomeObservation?: string;
  /** Learning (if learned). */
  learning?: string;
  /** Source recommendation id (if derived from existing recommendation). */
  sourceRecommendationId?: string;
}

// ---------------------------------------------------------------------------
// Opportunity Signal Store
// ---------------------------------------------------------------------------

/** Store for opportunity signals. */
export interface OpportunitySignalStore {
  /** All signals. */
  signals: OpportunitySignal[];
  /** Dismissed signal ids (for rediscovery prevention). */
  dismissedIds: Set<string>;
  /** Saved signal ids. */
  savedIds: Set<string>;
  /** Updated at. */
  updatedAt: string;
}

/** In-memory store. */
const signalStores: Map<string, OpportunitySignalStore> = new Map();

// ---------------------------------------------------------------------------
// Signal Creation
// ---------------------------------------------------------------------------

/**
 * Create an OpportunitySignal from an OpportunityRecommendation.
 */
export function createSignalFromRecommendation(params: {
  recommendation: OpportunityRecommendation;
  workspaceId: string;
  lifecycleState?: OpportunityLifecycleState;
}): OpportunitySignal {
  const now = new Date().toISOString();
  const state = params.lifecycleState ?? 'DETECTED';

  return {
    id: `sig-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 8)}`,
    workspaceId: params.workspaceId,
    category: params.recommendation.category,
    title: params.recommendation.title,
    description: params.recommendation.description,
    reason: params.recommendation.reason,
    evidence: params.recommendation.evidence,
    confidence: params.recommendation.confidence,
    expectedValue: params.recommendation.expectedValue,
    effort: params.recommendation.effort,
    goalAlignment: params.recommendation.goalAlignment,
    primaryAction: params.recommendation.primaryAction,
    actions: params.recommendation.actions,
    lifecycleState: state,
    transitions: {
      [state]: now,
    },
    createdAt: now,
    updatedAt: now,
    sourceRecommendationId: params.recommendation.id,
  };
}

/**
 * Get or create the signal store for a workspace.
 */
export function getSignalStore(workspaceId: string): OpportunitySignalStore {
  const existing = signalStores.get(workspaceId);
  if (existing) return existing;

  const store: OpportunitySignalStore = {
    signals: [],
    dismissedIds: new Set(),
    savedIds: new Set(),
    updatedAt: new Date().toISOString(),
  };
  signalStores.set(workspaceId, store);
  return store;
}

/**
 * Add a signal to the store.
 */
export function addSignal(workspaceId: string, signal: OpportunitySignal): OpportunitySignal {
  const store = getSignalStore(workspaceId);
  const existingIndex = store.signals.findIndex((s) => s.id === signal.id);

  if (existingIndex >= 0) {
    store.signals[existingIndex] = signal;
  } else {
    store.signals = [signal, ...store.signals].slice(0, 200);
  }

  store.updatedAt = new Date().toISOString();
  signalStores.set(workspaceId, store);
  return signal;
}

/**
 * Get all signals for a workspace.
 */
export function getAllSignals(workspaceId: string): OpportunitySignal[] {
  return getSignalStore(workspaceId).signals;
}

/**
 * Get active signals (not dismissed or learned).
 */
export function getActiveSignals(workspaceId: string): OpportunitySignal[] {
  const store = getSignalStore(workspaceId);
  return store.signals.filter((s) =>
    s.lifecycleState !== 'DISMISSED' && s.lifecycleState !== 'LEARNED'
  );
}

/**
 * Get active signals that are not yet saved or planned.
 */
export function getUnactedSignals(workspaceId: string): OpportunitySignal[] {
  const store = getSignalStore(workspaceId);
  return store.signals.filter((s) =>
    s.lifecycleState === 'DETECTED' ||
    s.lifecycleState === 'QUALIFIED'
  );
}

// ---------------------------------------------------------------------------
// Lifecycle Transitions
// ---------------------------------------------------------------------------

/**
 * Transition a signal to QUALIFIED.
 */
export function qualifySignal(workspaceId: string, signalId: string): OpportunitySignal | undefined {
  return transitionSignal(workspaceId, signalId, 'QUALIFIED');
}

/**
 * Dismiss a signal (prevents rediscovery).
 */
export function dismissSignal(params: {
  workspaceId: string;
  signalId: string;
  reason?: string;
}): OpportunitySignal | undefined {
  const store = getSignalStore(params.workspaceId);
  const signal = store.signals.find((s) => s.id === params.signalId);
  if (!signal) return undefined;

  signal.lifecycleState = 'DISMISSED';
  signal.transitions.DISMISSED = new Date().toISOString();
  signal.dismissedReason = params.reason;
  signal.updatedAt = new Date().toISOString();

  store.dismissedIds.add(signal.id);
  store.updatedAt = new Date().toISOString();
  signalStores.set(params.workspaceId, store);

  return signal;
}

/**
 * Save a signal (user wants to act later).
 */
export function saveSignal(params: {
  workspaceId: string;
  signalId: string;
  savedPlanId?: string;
}): OpportunitySignal | undefined {
  const store = getSignalStore(params.workspaceId);
  const signal = store.signals.find((s) => s.id === params.signalId);
  if (!signal) return undefined;

  signal.lifecycleState = 'SAVED';
  signal.transitions.SAVED = new Date().toISOString();
  signal.savedPlanId = params.savedPlanId;
  signal.updatedAt = new Date().toISOString();

  store.savedIds.add(signal.id);
  store.updatedAt = new Date().toISOString();
  signalStores.set(params.workspaceId, store);

  return signal;
}

/**
 * Mark a signal as PLANNED (converted to a plan).
 */
export function planSignal(params: {
  workspaceId: string;
  signalId: string;
  planId: string;
}): OpportunitySignal | undefined {
  const store = getSignalStore(params.workspaceId);
  const signal = store.signals.find((s) => s.id === params.signalId);
  if (!signal) return undefined;

  signal.lifecycleState = 'PLANNED';
  signal.transitions.PLANNED = new Date().toISOString();
  signal.savedPlanId = params.planId;
  signal.updatedAt = new Date().toISOString();

  store.updatedAt = new Date().toISOString();
  signalStores.set(params.workspaceId, store);

  return signal;
}

/**
 * Mark a signal as ACTED (plan was executed).
 */
export function actSignal(params: {
  workspaceId: string;
  signalId: string;
  executionId: string;
}): OpportunitySignal | undefined {
  const store = getSignalStore(params.workspaceId);
  const signal = store.signals.find((s) => s.id === params.signalId);
  if (!signal) return undefined;

  signal.lifecycleState = 'ACTED';
  signal.transitions.ACTED = new Date().toISOString();
  signal.actedExecutionId = params.executionId;
  signal.updatedAt = new Date().toISOString();

  store.updatedAt = new Date().toISOString();
  signalStores.set(params.workspaceId, store);

  return signal;
}

/**
 * Mark a signal as OUTCOME_OBSERVED.
 */
export function observeOutcome(params: {
  workspaceId: string;
  signalId: string;
  observation: string;
}): OpportunitySignal | undefined {
  const store = getSignalStore(params.workspaceId);
  const signal = store.signals.find((s) => s.id === params.signalId);
  if (!signal) return undefined;

  signal.lifecycleState = 'OUTCOME_OBSERVED';
  signal.transitions.OUTCOME_OBSERVED = new Date().toISOString();
  signal.outcomeObservation = params.observation;
  signal.updatedAt = new Date().toISOString();

  store.updatedAt = new Date().toISOString();
  signalStores.set(params.workspaceId, store);

  return signal;
}

/**
 * Mark a signal as LEARNED.
 */
export function learnSignal(params: {
  workspaceId: string;
  signalId: string;
  learning: string;
}): OpportunitySignal | undefined {
  const store = getSignalStore(params.workspaceId);
  const signal = store.signals.find((s) => s.id === params.signalId);
  if (!signal) return undefined;

  signal.lifecycleState = 'LEARNED';
  signal.transitions.LEARNED = new Date().toISOString();
  signal.learning = params.learning;
  signal.updatedAt = new Date().toISOString();

  store.updatedAt = new Date().toISOString();
  signalStores.set(params.workspaceId, store);

  return signal;
}

/**
 * Generic signal transition.
 */
function transitionSignal(
  workspaceId: string,
  signalId: string,
  newState: OpportunityLifecycleState
): OpportunitySignal | undefined {
  const store = getSignalStore(workspaceId);
  const signal = store.signals.find((s) => s.id === signalId);
  if (!signal) return undefined;

  signal.lifecycleState = newState;
  signal.transitions[newState] = new Date().toISOString();
  signal.updatedAt = new Date().toISOString();

  store.updatedAt = new Date().toISOString();
  signalStores.set(workspaceId, store);

  return signal;
}

// ---------------------------------------------------------------------------
// Rediscovery Prevention
// ---------------------------------------------------------------------------

/**
 * Check if a signal has been dismissed (prevents rediscovery).
 */
export function isDismissed(workspaceId: string, signalId: string): boolean {
  const store = getSignalStore(workspaceId);
  return store.dismissedIds.has(signalId);
}

/**
 * Filter out dismissed signals from a list of recommendations.
 * This is the key function for Opportunity Radar integration.
 */
export function filterDismissedSignals<T extends { id: string }>(
  workspaceId: string,
  recommendations: T[]
): T[] {
  const store = getSignalStore(workspaceId);
  return recommendations.filter((r) => !store.dismissedIds.has(r.id));
}

/**
 * Check if a signal id matches a dismissed signal (by id or by source recommendation id).
 */
export function isSignalDismissedBySourceId(workspaceId: string, sourceRecommendationId: string): boolean {
  const store = getSignalStore(workspaceId);
  return store.signals.some(
    (s) => s.sourceRecommendationId === sourceRecommendationId && s.lifecycleState === 'DISMISSED'
  );
}

// ---------------------------------------------------------------------------
// Store Management
// ---------------------------------------------------------------------------

/**
 * Export the signal store for a workspace.
 */
export function exportSignalStore(workspaceId: string): OpportunitySignalStore {
  return getSignalStore(workspaceId);
}

/**
 * Import a signal store into a workspace.
 */
export function importSignalStore(workspaceId: string, store: OpportunitySignalStore): void {
  signalStores.set(workspaceId, {
    signals: store.signals,
    dismissedIds: store.dismissedIds,
    savedIds: store.savedIds,
    updatedAt: new Date().toISOString(),
  });
}

/**
 * Clear the store for a workspace (testing only).
 */
export function clearSignalStore(workspaceId: string): void {
  signalStores.delete(workspaceId);
}
